kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfsvolume
  annotations:
    volume.beta.kubernetes.io/storage-class: "hchiramm"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
